### ISSUE TITLE
Correct response message to client

### ISSUE THREAD

**Issue by AmoebaProtozoa** [DigitalChinaOpenSource/TiDB-for-PostgreSQL#35]
### Description
Before Postgres sends data result back to client, it will first give description about the data it’s returning, aka Row description. After sending the data row, it will send a command completion along with a tag tells user how many rows has been modified.
Currently, both our row description and data row information are incomplete/ incorrect. This issue address that.

### Which Module
Server

### Task List

- [ ] Column Index in row description message
- [ ] Column Length in row description message
- [ ] Type Modifier in row description message
- [ ] Tag in command completion message
- [ ] Add Unit Test in conn_test for all the fields above

### Reference
Below are our current response message when running simple select statement on TiDB for PG
![F8BE0240-8335-41C7-81FB-62AF0F21666F](https://user-images.githubusercontent.com/8039876/129301754-4a53a67d-d3ea-48a8-84f6-3f077d62e744.png)
Here are the expected message captured from Postgres 12
![7B1FAEC5-0D96-44D0-A9FA-F2BDA6FCB717](https://user-images.githubusercontent.com/8039876/129301765-89dec278-f2f7-4720-b525-f628e40329c3.png)
