### ISSUE TITLE
To support PG compliant SQL DML statement

### ISSUE THREAD

**Issue by RogueJin** [DigitalChinaOpenSource/TiDB-for-PostgreSQL#40]
## Development Task
###Description
Since TiDB is Mysql compliant database, we need to adjust DCParser yacc paser files to remove mysql keywords and add pg keywords, and then implement the keywords logic functions in TiDB4PG project.

###Task List
####DCParser:
- [ ] Delete Statement Parser
- [ ] Select Statement Parser
- [ ] Insert Statement Parser
- [ ] Update Statement Parser

####TiDB4PG
#####Keywords Implement
- [ ] Returning
